<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->seedMunicipality();
    }

    public function seedMunicipality(){
        $municipalities = [
            // Province 1
            ['name' => 'Phungling Municipality', 'district_id' => 1],
            ['name' => 'Phidim Municipality', 'district_id' => 2],
            ['name' => 'Illam Municipality', 'district_id' => 3],
            ['name' => 'Mai Municipality', 'district_id' => 3],
            ['name' => 'Deumai Municipality', 'district_id' => 3],
            ['name' => 'Suryodaya Municipality', 'district_id' => 3],
            ['name' => 'Shivasataxi Municipality', 'district_id' => 4],
            ['name' => 'Bhadrapur Municipality', 'district_id' => 4],
            ['name' => 'Kankai Municipality', 'district_id' => 4],
            ['name' => 'Birtamod Municipality', 'district_id' => 4],
            ['name' => 'Mechinagar Municipality', 'district_id' => 4],
            ['name' => 'Damak Municipality', 'district_id' => 4],
            ['name' => 'Arjundhara Municipality', 'district_id' => 4],
            ['name' => 'Gauradhaha Municipality', 'district_id' => 4],
            ['name' => 'Dharmadevi Municipality', 'district_id' => 5],
            ['name' => 'Madi Municipality', 'district_id' => 5],
            ['name' => 'Panchakhapan Municipality', 'district_id' => 5],
            ['name' => 'Chainpur Municipality', 'district_id' => 5],
            ['name' => 'Khandbari Municipality', 'district_id' => 5],
            ['name' => 'Solududhakunda Municipality', 'district_id' => 6],
            ['name' => 'Siddhicharan Municipality', 'district_id' => 7],
            ['name' => 'Laligurans Municipality', 'district_id' => 8],
            ['name' => 'Myanglung Municipality', 'district_id' => 8],
            ['name' => 'Shadananda Municipality', 'district_id' => 9],
            ['name' => 'Bhojpur Municipality', 'district_id' => 9],
            ['name' => 'Halesi Tuwachung Municipality', 'district_id' => 10],
            ['name' => 'Diktel Rupakot Majhuwagadhi Municipality', 'district_id' => 10],
            ['name' => 'Pakhribas Municipality', 'district_id' => 11],
            ['name' => 'Mahalaxmi Municipality', 'district_id' => 11],
            ['name' => 'Dhankuta Municipality', 'district_id' => 11],
            ['name' => 'Chaudandigadhi Municipality', 'district_id' => 12],
            ['name' => 'Triyuga Municipality', 'district_id' => 12],
            ['name' => 'Katari Municipality', 'district_id' => 12],
            ['name' => 'Belaka Municipality', 'district_id' => 12],
            ['name' => 'Letang Municipality', 'district_id' => 13],
            ['name' => 'Sunwarshi Municipality', 'district_id' => 13],
            ['name' => 'Rangeli Municipality', 'district_id' => 13],
            ['name' => 'Patahrishanishchare Municipality', 'district_id' => 13],
            ['name' => 'Uralabari Municipality', 'district_id' => 13],
            ['name' => 'Belbari Municipality', 'district_id' => 13],
            ['name' => 'Sundarharaicha Municipality', 'district_id' => 13],
            ['name' => 'Ratuwamai Municipality', 'district_id' => 13],
            ['name' => 'Ramdhuni Municipality', 'district_id' => 14],
            ['name' => 'Barahchhetra Municipality', 'district_id' => 14],
            ['name' => 'Duhabi Municipality', 'district_id' => 14],
            ['name' => 'Inaruwa Municipality', 'district_id' => 14],

            // Province 2
            ['name' => 'Hanumannagar Kankalini Municipality', 'district_id' => 15],
            ['name' => 'Kanchanrup Municipality', 'district_id' => 15],
            ['name' => 'Rajbiraj Municipality', 'district_id' => 15],
            ['name' => 'Khadak Municipality', 'district_id' => 15],
            ['name' => 'Dakneshwori Municipality', 'district_id' => 15],
            ['name' => 'Saptakoshi Municipality', 'district_id' => 15],
            ['name' => 'Surunga Municipality', 'district_id' => 15],
            ['name' => 'Shambhunath Municipality', 'district_id' => 15],
            ['name' => 'Bode Barsain Municipality', 'district_id' => 15],
            ['name' => 'Mirchaiya Municipality', 'district_id' => 16],
            ['name' => 'Lahan Municipality', 'district_id' => 16],
            ['name' => 'Siraha Municipality', 'district_id' => 16],
            ['name' => 'Dhangadhimai Municipality', 'district_id' => 16],
            ['name' => 'Kalyanpur Municipality', 'district_id' => 16],
            ['name' => 'Karjanha Municipality', 'district_id' => 16],
            ['name' => 'Golbazar Municipality', 'district_id' => 16],
            ['name' => 'Sukhipur Municipality', 'district_id' => 16],
            ['name' => 'Nagarain Municipality', 'district_id' => 17],
            ['name' => 'Ganeshman Charnath Municipality', 'district_id' => 17],
            ['name' => 'Mithila Municipality', 'district_id' => 17],
            ['name' => 'Dhanusadham Municipality', 'district_id' => 17],
            ['name' => 'Bideha Municipality', 'district_id' => 17],
            ['name' => 'Sabaila Municipality', 'district_id' => 17],
            ['name' => 'Hansapur Municipality', 'district_id' => 17],
            ['name' => 'Sahidnagar Municipality', 'district_id' => 17],
            ['name' => 'Chhireshwornath Municipality', 'district_id' => 17],
            ['name' => 'Gaushala Municipality', 'district_id' => 18],
            ['name' => 'Ramgopalpur Municipality', 'district_id' => 18],
            ['name' => 'Aurahi Municipality', 'district_id' => 18],
            ['name' => 'Bardibas Municipality', 'district_id' => 18],
            ['name' => 'Bhangaha Municipality', 'district_id' => 18],
            ['name' => 'Jaleswor Municipality', 'district_id' => 18],
            ['name' => 'Balwa Municipality', 'district_id' => 18],
            ['name' => 'Manra Siswa Municipality', 'district_id' => 18],
            ['name' => 'Matihani Municipality', 'district_id' => 18],
            ['name' => 'Loharpatti Municipality', 'district_id' => 18],
            ['name' => 'Barahathawa Municipality', 'district_id' => 19],
            ['name' => 'Haripur Municipality', 'district_id' => 19],
            ['name' => 'Ishworpur Municipality', 'district_id' => 19],
            ['name' => 'Lalbandi Municipality', 'district_id' => 19],
            ['name' => 'Malangawa Municipality', 'district_id' => 19],
            ['name' => 'Kabilasi Municipality', 'district_id' => 19],
            ['name' => 'Bagmati Municipality', 'district_id' => 19],
            ['name' => 'Hariwan Municipality', 'district_id' => 19],
            ['name' => 'Balara Municipality', 'district_id' => 19],
            ['name' => 'Haripurwa Municipality', 'district_id' => 19],
            ['name' => 'Godaita Municipality', 'district_id' => 19],
            ['name' => 'Katahariya Municipality', 'district_id' => 20],
            ['name' => 'Maulapur Municipality', 'district_id' => 20],
            ['name' => 'Madhav Narayan Municipality', 'district_id' => 20],
            ['name' => 'Gaur Municipality', 'district_id' => 20],
            ['name' => 'Gujara Municipality', 'district_id' => 20],
            ['name' => 'Garuda Municipality', 'district_id' => 20],
            ['name' => 'Ishanath Municipality', 'district_id' => 20],
            ['name' => 'Chandrapur Municipality', 'district_id' => 20],
            ['name' => 'Gonahi Municipality', 'district_id' => 20],
            ['name' => 'Brindaban Municipality', 'district_id' => 20],
            ['name' => 'Rajpur Municipality', 'district_id' => 20],
            ['name' => 'Rajdevi Municipality', 'district_id' => 20],
            ['name' => 'Gadhimai Municipality', 'district_id' => 20],
            ['name' => 'Phatuwa Bijayapur Municipality', 'district_id' => 20],
            ['name' => 'Baudhimai Municipality', 'district_id' => 20],
            ['name' => 'Paroha Municipality', 'district_id' => 20],
            ['name' => 'Pacharauta Municipality', 'district_id' => 21],
            ['name' => 'Nijgadh Municipality', 'district_id' => 21],
            ['name' => 'Simraungadh Municipality', 'district_id' => 21],
            ['name' => 'Mahagadhimai Municipality', 'district_id' => 21],
            ['name' => 'Kolhabi Municipality', 'district_id' => 21],
            ['name' => 'Bahudaramai Municipality', 'district_id' => 22],
            ['name' => 'Pokhariya Municipality', 'district_id' => 22],
            ['name' => 'Parsagadhi Municipality', 'district_id' => 22],

            // Province 3
            ['name' => 'Jiri Municipality', 'district_id' => 23],
            ['name' => 'Bhimeshwor Municipality', 'district_id' => 23],
            ['name' => 'Chautara SangachokGadhi Municipality', 'district_id' => 24],
            ['name' => 'Barhabise Municipality', 'district_id' => 24],
            ['name' => 'Melamchi Municipality', 'district_id' => 24],
            ['name' => 'Nilakantha Municipality', 'district_id' => 25],
            ['name' => 'Dhunibesi Municipality', 'district_id' => 25],
            ['name' => 'Belkotgadhi Municipality', 'district_id' => 26],
            ['name' => 'Bidur Municipality', 'district_id' => 26],
            ['name' => 'Kirtipur Municipality', 'district_id' => 27],
            ['name' => 'Shankharapur Municipality', 'district_id' => 27],
            ['name' => 'Nagarjun Municipality', 'district_id' => 27],
            ['name' => 'Budhanilakantha Municipality', 'district_id' => 27],
            ['name' => 'Tarakeshwor Municipality', 'district_id' => 27],
            ['name' => 'Tokha Municipality', 'district_id' => 27],
            ['name' => 'Chandragiri Municipality', 'district_id' => 27],
            ['name' => 'Gokarneshwor Municipality', 'district_id' => 27],
            ['name' => 'Changunarayan Municipality', 'district_id' => 28],
            ['name' => 'Suryabinayak Municipality', 'district_id' => 28],
            ['name' => 'Bhaktapur Municipality', 'district_id' => 28],
            ['name' => 'Madhyapur Thimi Municipality', 'district_id' => 28],
            ['name' => 'Mahalaxmi Municipality', 'district_id' => 29],
            ['name' => 'Godawari Municipality', 'district_id' => 29],
            ['name' => 'Banepa Municipality', 'district_id' => 30],
            ['name' => 'Mandandeupur Municipality', 'district_id' => 30],
            ['name' => 'Dhulikhel Municipality', 'district_id' => 30],
            ['name' => 'Panauti Municipality', 'district_id' => 30],
            ['name' => 'Namobuddha Municipality', 'district_id' => 30],
            ['name' => 'Panchkhal Municipality', 'district_id' => 30],
            ['name' => 'Manthali Municipality', 'district_id' => 31],
            ['name' => 'Ramechhap Municipality', 'district_id' => 31],
            ['name' => 'Dudhouli Municipality', 'district_id' => 32],
            ['name' => 'Kamalamai Municipality', 'district_id' => 32],
            ['name' => 'Thaha Municipality', 'district_id' => 33],
            ['name' => 'Kalika Municipality', 'district_id' => 34],
            ['name' => 'Khairahani Municipality', 'district_id' => 34],
            ['name' => 'Madi Municipality', 'district_id' => 34],
            ['name' => 'Rapti Municipality', 'district_id' => 34],
            ['name' => 'Ratnanagar Municipality', 'district_id' => 34],

            // Province 4
            ['name' => 'Palungtar Municipality', 'district_id' => 36],
            ['name' => 'Gorkha Municipality', 'district_id' => 36],
            ['name' => 'Beni Municipality', 'district_id' => 37],
            ['name' => 'Sundarbazar Municipality', 'district_id' => 38],
            ['name' => 'Besishahar Municipality', 'district_id' => 38],
            ['name' => 'Rainas Municipality', 'district_id' => 38],
            ['name' => 'MadhyaNepal Municipality', 'district_id' => 38],
            ['name' => 'Byas Municipality', 'district_id' => 39],
            ['name' => 'Shuklagandaki Municipality', 'district_id' => 39],
            ['name' => 'Bhimad Municipality', 'district_id' => 39],
            ['name' => 'Bhanu Municipality', 'district_id' => 39],
            ['name' => 'Madhyabindu Municipality', 'district_id' => 40],
            ['name' => 'Devchuli Municipality', 'district_id' => 40],
            ['name' => 'Gaidakot Municipality', 'district_id' => 40],
            ['name' => 'Kawasoti Municipality', 'district_id' => 40],
            ['name' => 'Putalibazar Municipality', 'district_id' => 41],
            ['name' => 'Bhirkot Municipality', 'district_id' => 41],
            ['name' => 'Galyang Municipality', 'district_id' => 41],
            ['name' => 'Chapakot Municipality', 'district_id' => 41],
            ['name' => 'Waling Municipality', 'district_id' => 41],
            ['name' => 'Kushma Municipality', 'district_id' => 42],
            ['name' => 'Phalebas Municipality', 'district_id' => 42],
            ['name' => 'Jaimuni Municipality', 'district_id' => 43],
            ['name' => 'Baglung Municipality', 'district_id' => 43],
            ['name' => 'Galkot Municipality', 'district_id' => 43],
            ['name' => 'Dhorpatan Municipality', 'district_id' => 43],

            // Province 5
            ['name' => 'Rolpa Municipality', 'district_id' => 47],
            ['name' => 'Pyuthan Municipality', 'district_id' => 48],
            ['name' => 'Sworgadwary Municipality', 'district_id' => 48],
            ['name' => 'Resunga Municipality', 'district_id' => 49],
            ['name' => 'Musikot Municipality', 'district_id' => 49],
            ['name' => 'Bhumekasthan Municipality', 'district_id' => 50],
            ['name' => 'Sitganga Municipality', 'district_id' => 50],
            ['name' => 'Sandhikharka Municipality', 'district_id' => 50],
            ['name' => 'Tansen Municipality', 'district_id' => 51],
            ['name' => 'Rampur Municipality', 'district_id' => 51],
            ['name' => 'Bardaghat Municipality', 'district_id' => 52],
            ['name' => 'Sunwal Municipality', 'district_id' => 52],
            ['name' => 'Ramgram Municipality', 'district_id' => 52],
            ['name' => 'Lumbini Sanskritik Municipality', 'district_id' => 53],
            ['name' => 'Devdaha Municipality', 'district_id' => 53],
            ['name' => 'Sainamaina Municipality', 'district_id' => 53],
            ['name' => 'Siddharthanagar Municipality', 'district_id' => 53],
            ['name' => 'Tillotama Municipality', 'district_id' => 53],
            ['name' => 'Shivaraj Municipality', 'district_id' => 54],
            ['name' => 'Kapilbastu Municipality', 'district_id' => 54],
            ['name' => 'Buddhabhumi Municipality', 'district_id' => 54],
            ['name' => 'Maharajgunj Municipality', 'district_id' => 54],
            ['name' => 'Banganga Municipality', 'district_id' => 54],
            ['name' => 'Krishnanagar Municipality', 'district_id' => 54],
            ['name' => 'Lamahi Municipality', 'district_id' => 55],
            ['name' => 'Kohalpur Municipality', 'district_id' => 56],
            ['name' => 'Thakurbaba Municipality', 'district_id' => 57],
            ['name' => 'Bansagadhi Municipality', 'district_id' => 57],
            ['name' => 'Barbardiya Municipality', 'district_id' => 57],
            ['name' => 'Rajapur Municipality', 'district_id' => 57],
            ['name' => 'Madhuwan Municipality', 'district_id' => 57],
            ['name' => 'Gulariya Municipality', 'district_id' => 57],

            // Province 6
            ['name' => 'Tripurasundari Municipality', 'district_id' => 59],
            ['name' => 'Thuli Bheri Municipality', 'district_id' => 59],
            ['name' => 'Chhayanath Rara Municipality', 'district_id' => 60],
            ['name' => 'Chandannath Municipality', 'district_id' => 61],
            ['name' => 'Khandachakra Municipality', 'district_id' => 62],
            ['name' => 'Raskot Municipality', 'district_id' => 62],
            ['name' => 'Tilagufa Municipality', 'district_id' => 62],
            ['name' => 'Aathabis Municipality', 'district_id' => 63],
            ['name' => 'Dullu Municipality', 'district_id' => 63],
            ['name' => 'Chamunda Bindrasaini Municipality', 'district_id' => 63],
            ['name' => 'Narayan Municipality', 'district_id' => 63],
            ['name' => 'Nalagad Municipality', 'district_id' => 64],
            ['name' => 'Bheri Municipality', 'district_id' => 64],
            ['name' => 'Chhedagad Municipality', 'district_id' => 64],
            ['name' => 'Aathbiskot Municipality', 'district_id' => 65],
            ['name' => 'Chaurjahari Municipality', 'district_id' => 65],
            ['name' => 'Musikot Municipality', 'district_id' => 65],
            ['name' => 'Sharada Municipality', 'district_id' => 66],
            ['name' => 'Bangad Kupinde Municipality', 'district_id' => 66],
            ['name' => 'Bagchaur Municipality', 'district_id' => 66],
            ['name' => 'Gurbhakot Municipality', 'district_id' => 67],
            ['name' => 'Panchpuri Municipality', 'district_id' => 67],
            ['name' => 'Bheriganga Municipality', 'district_id' => 67],
            ['name' => 'Lekbeshi Municipality', 'district_id' => 67],
            ['name' => 'Birendranagar Municipality', 'district_id' => 67],

            // Province 7
            ['name' => 'Badimalika Municipality', 'district_id' => 69],
            ['name' => 'Tribeni Municipality', 'district_id' => 69],
            ['name' => 'Budhiganga Municipality', 'district_id' => 69],
            ['name' => 'Budhinanda Municipality', 'district_id' => 69],
            ['name' => 'JayaPrithivi Municipality', 'district_id' => 70],
            ['name' => 'Bungal Municipality', 'district_id' => 70],
            ['name' => 'Mahakali Municipality', 'district_id' => 71],
            ['name' => 'Shailyashikhar Municipality', 'district_id' => 71],
            ['name' => 'Melauli Municipality', 'district_id' => 72],
            ['name' => 'Dasharathchanda Municipality', 'district_id' => 72],
            ['name' => 'Purchaudi Municipality', 'district_id' => 72],
            ['name' => 'Patan Municipality', 'district_id' => 72],
            ['name' => 'Amargadhi Municipality', 'district_id' => 73],
            ['name' => 'Parashuram Municipality', 'district_id' => 73],
            ['name' => 'Dipayal Silgadi Municipality', 'district_id' => 74],
            ['name' => 'Shikhar Municipality', 'district_id' => 74],
            ['name' => 'Sanphebagar Municipality', 'district_id' => 75],
            ['name' => 'Mangalsen Municipality', 'district_id' => 75],
            ['name' => 'Kamalbazar Municipality', 'district_id' => 75],
            ['name' => 'Panchadewal Binayak Municipality', 'district_id' => 75],
            ['name' => 'Tikapur Municipality', 'district_id' => 76],
            ['name' => 'Ghodaghodi Municipality', 'district_id' => 76],
            ['name' => 'Bhajani Municipality', 'district_id' => 76],
            ['name' => 'Gauriganga Municipality', 'district_id' => 76],
            ['name' => 'Godawari Municipality', 'district_id' => 76],
            ['name' => 'Lamkichuha Municipality', 'district_id' => 76],
            ['name' => 'Punarbas Municipality', 'district_id' => 77],
            ['name' => 'Krishnapur Municipality', 'district_id' => 77],
            ['name' => 'Mahakali Municipality', 'district_id' => 77],
            ['name' => 'Bedkot Municipality', 'district_id' => 77],
            ['name' => 'Belauri Municipality', 'district_id' => 77],
            ['name' => 'Bhimdatta Municipality', 'district_id' => 77],
            ['name' => 'Shuklaphanta Municipality', 'district_id' => 77],
        ];
        DB::table('municipalities')->insert($municipalities);
    }
}
